language: ruby

cache: bundler

sudo: false

rvm:
  - ruby-head
  - 2.5.3
  - 2.4.5
  - 2.3.8

gemfile:
  - gemfiles/jekyll_v3.gemfile
  - gemfiles/jekyll_v2.gemfile
  - gemfiles/jekyll_v1.gemfile

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/jekyll_v2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/jekyll_v1.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/jekyll_v2.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/jekyll_v1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/jekyll_v2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/jekyll_v1.gemfile
  allow_failures:
    - rvm: ruby-head
